[package]
name = "aim_trainer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_rand = { workspace = true }
rand = { workspace = true }
derive_more = { workspace = true }
raylib = { workspace = true }
thiserror = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }

schema = { path = "../schema" }
ref_asset = { path = "../ref_asset" }

[lints]
workspace = true
